source 'https://rubygems.org'
source 'http://filestore.pl.codeproject.com/file_store/gemserver'

gem 'rails', '3.2.3'
gem 'rails_config'

group :assets do
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  gem 'therubyracer', :platform => :ruby
  gem 'less-rails'
  gem 'less-rails-bootstrap'
  gem 'haml-rails'

  gem 'uglifier', '>= 1.0.3'
  gem "jquery-fileupload-rails"
end


group :development, :test do
  gem 'terminal-notifier-guard'
  gem 'rspec-rails'
  gem 'protobuf-rspec'
  gem 'jasmine'
  gem 'guard-coffeescript'

  # To use debugger
  gem 'linecache19', "=0.5.13"
  gem 'ruby-debug-base19', "=0.11.26"
  gem 'ruby-debug19', :require => 'ruby-debug'
end

group :development do
  gem 'guard-rspec'
  gem 'fabrication'
end

gem 'faker'

gem 'jquery-rails'
gem 'rugged', :git => 'git://github.com/libgit2/rugged.git', :branch => 'development', :submodules => true

gem 'rubypython', '~> 0.5.999'
gem 'github-linguist', :require => 'linguist'

gem "mongoid", "~> 3.0.0"
gem 'mongoid_slug', "~> 1.0.0.rc2"

gem 'protobuf'

gem 'rubyzip'
gem 'open4'

gem 'sidekiq'
gem 'sinatra', require: false
gem 'slim'

gem 'backbone-on-rails'

# gem 'thin'
# gem 'eventmachine'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

gem 'coderay'
gem 'pygments.rb', :git => 'git://github.com/krzyczak/pygments.rb.git'
